spring:
  datasource:
    url: jdbc:mysql://localhost/online_quiz?createDatabaseIfNotExist=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: org.hibernate.dialect.MySQL57Dialect
    username: admin
    password: Admin@1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: 7777
