spring:
  datasource:
    url: jdbc:mysql://localhost/online_quiz?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: org.hibernate.dialect.MySQL57Dialect
    username: admin
    password: Admin@1234

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 7777
